name = "GaussianExpansionCavityMethod"
uuid = "e07873fc-887d-4a56-bff1-02ba28e82f55"
authors = ["Mattia Tarabolo <mattia.tarabolo@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
